name: Run tests

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 17 ]

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Build KanbanQL
        run: gradle build
        env:
          CI: true

      - name: Run Unit-Tests
        run: gradle test
        env:
          CI: true
